apiVersion: v1
kind: ConfigMap
metadata:
  name: beaesthetic-analytics-config
  namespace: beaesthetic
data:
  ANALYTICS_MONGODB_DATABASE: "appointments-v2"
  ANALYTICS_ENVIRONMENT: "production"
  ANALYTICS_LOG_LEVEL: "INFO"